[webservers]
web-1 ansible_host=10.0.1.18 fqdn=fhmoh4ll5rgcn5rlajci.auto.internal
web-2 ansible_host=10.0.1.33 fqdn=fhmnjf0r6tvtkf0n4smc.auto.internal

[databases]
main ansible_host=10.0.1.5 fqdn=fhmo9f77mblv1fk8hf9g.auto.internal
replica ansible_host=10.0.1.22 fqdn=fhmhjkhs22rgfo432je8.auto.internal

[storage]
storage ansible_host=10.0.1.16 fqdn=fhmtcg5877nlkgqbcrh7.auto.internal

