---
all:
  children:
    deb:
      hosts:
        deb_host:
          ansible_host: localhost
          ansible_port: 2222
          ansible_user: ansible
          ansible_password: ansible
    el:
      hosts:
        el_host:
          ansible_host: localhost
          ansible_port: 2223
          ansible_user: ansible
          ansible_password: ansible
    local:
      hosts:
        localhost:
          ansible_connection: local
    fedora:
      hosts:
        fedora_host:
          ansible_host: localhost
          ansible_port: 2224
          ansible_user: ansible
          ansible_password: ansible
