events {
    worker_connections 1024;
}

http {
    upstream security {
        server security:5000;
    }
    upstream uploader {
        server uploader:5000;
    }
    upstream minio {
        server minio:9000;
    }

    server {
        listen 80;
        server_name localhost;

        location = /register {
            proxy_pass http://security/v1/user;
        }

        location = /token {
            proxy_pass http://security/v1/token;
        }

        location = /auth {
            internal;
            proxy_pass http://security/v1/token/validation;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header Authorization $http_authorization;
        }

        location = /user {
            auth_request /auth;
            proxy_pass http://security/v1/user;
        }

        location = /upload {
            auth_request /auth;
            proxy_pass http://uploader/v1/upload;
        }

        location ~ ^/images/(.*)$ {
            auth_request /auth;
            proxy_pass http://minio/images/$1;
        }
    }
}
