apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-exchange
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data-exchange-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-exchange
spec:
  volumeName: pv-data-exchange
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-pvc
  template:
    metadata:
      labels:
        app: data-exchange-pvc
    spec:
      containers:
      - name: busybox-writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            echo $(date) >> /mnt/data.txt
            sleep 5
          done
        volumeMounts:
        - name: pv-storage
          mountPath: /mnt
      - name: multitool-reader
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args: ["tail -f /mnt/data.txt"]
        volumeMounts:
        - name: pv-storage
          mountPath: /mnt
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pvc-data-exchange
