apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-frontend
  labels:
    app: {{ include "myapp.name" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "myapp.name" . }}-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
